# cadastrar preço do produto (Teclado Mecânico Wireless)
POST http://localhost:5002/precos
Content-Type: application/json

{ "produtoId": "6a373b27a31b6778bc110729", "valor": 349.90 }

###

# cadastrar preço do produto (Monitor 27)
POST http://localhost:5002/precos
Content-Type: application/json

{ "produtoId": "6a373b3ca31b6778bc11072a", "valor": 525.50 }

###

# listar preço do produto 1
GET http://localhost:5002/precos/6a373b27a31b6778bc110729

###

# listar preço do produto 2
GET http://localhost:5002/precos/6a373b3ca31b6778bc11072a


