# create price for product 1)
POST http://localhost:5002/prices
Content-Type: application/json

{ "productId": "6a39ad29bc352605b53472d7", "value": 228.90 }

###

# create price for product 2
POST http://localhost:5002/prices
Content-Type: application/json

{ "productId": "6a39ad29bc352605b53472d7", "value": 355.50 }

###

# list price of product 1
GET http://localhost:5002/prices/6a39c4286977d602a9eb8538

###

# list price of product 2
GET http://localhost:5002/prices/6a39ad29bc352605b53472d7


###
GET http://localhost:5002/health

###